version: "3.8"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  node-app:
    container_name: node-app
    restart: unless-stopped
    image: server:latest
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    restart: unless-stopped
    image: frontend:latest
    build:
      context: frontend
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - node-app
